---
- hosts: web
  become: yes
  tasks:

  - name: install httpd 
    yum: name=httpd  state=installed 


  - name: start httpd service
    service: name=httpd  state=started


  - name: copy home page
    template: src=/home/ansible/index.html    dest=/var/www/html
